#!/bin/bash

# Define default variable values
REDIRECTURL="${REDIRECTURL:-http://www.gamestv.org/download/repository/et/}"
STARTMAP="${STARTMAP:-radar}"
MAP_PORT="${MAP_PORT:-27960}"
IP_MAX_CLIENTS="${IP_MAX_CLIENTS:-3}"

CONFIG_PATH="/home/game/etpro/server.cfg"


# Find and replace all variables wrapped with % with their value
for env in `compgen -v`; do
    # Ensure string doesn't contain split delimiter
    if [[ "${!env}" != *"|"* ]] && [[ "${env}" != "IFS" ]]; then
        sed -i "s|%${env}%|${!env}|g" ${CONFIG_PATH}
    fi
done


# If the MAPS variable is defined loop through the downloads
if [ -n "$MAPS" ]; then
    IFS=":" # Split on ':'
    for map in $MAPS; do
        # wget each map
        wget -P etmain "${REDIRECTURL}/etmain/${map}.pk3"
    done
fi


# Replace un-substituted variables with nothing
sed -i 's/%[A-Z]*%//g' ${CONFIG_PATH}


# Enable noquery if necessary
if [[ "${NOQUERY}" == "true" ]]; then
    export LD_PRELOAD="/home/game/libnoquery.so"
fi


# Execute Enemy Territory
exec ./ettv.x86 +set dedicated 2 +set vm_game 0 +set sv_autoUpdate 0 +set net_ip 0.0.0.0 +set net_port ${MAP_PORT} +set sv_maxclients 32 +set fs_game etpro +set sv_punkbuster 0 +exec server.cfg
